# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

	steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Install .NET 8.0
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: '8.0.x'

  - name: Build, Tests, Cover, Pack and Publish (on push tag)
    shell: bash
    run: |
      dotnet tool install --global dotnet-releaser
      dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" src/dotnet-releaser.toml
